### ISSUE TITLE
YugabyteDB Managed 入門の内容確認

### ISSUE THREAD

**Issue by tichimura** [yugabytedb-japan/yugabytedb-japan.github.io#5]
# Problem Description
いくつか気になる点があったので、コメントします。

# Issues 
- line: 82
`以下は、SandboxとDedicated (有償環境) の機能比較です。`
の後に比較表が入る予定でしょうか。

- line: 102
`Network Accessページが表示されます。[Add Current IP Address]をクリックして、自分の端末のIPアドレスをアクセス許可リストに追加してください。`
ここは自動的に取得されるのでしたでしょうか。

- line: 150
` これでCloud Shellからクラスタにアクセスすることができました。`
の部分がハイライトされているようです。

# Background
# Expectation

・上記指摘内容の更新及び確認

**Comment by tichimura** [comment]
@arisa-i お願いします。

**Comment by arisa-i** [comment]
上ふたつは修正済みですが、3つ目の原因がわかっていません。Google Docレベル上は問題ないのですが、claatで直せないようだったら直接mdを直すようにします。

**Comment by arisa-i** [comment]
indentを削除することでハイライトを解除することができました。
